CREATE TABLE prices (
    ID 			    INT AUTO_INCREMENT PRIMARY KEY,
	BRAND_ID 		INT	NOT NULL,
	START_DATE      TIMESTAMP  NOT NULL,
	END_DATE        TIMESTAMP  NOT NULL,
	PRICE_LIST		INT	NOT NULL,
	PRODUCT_ID		INT	NOT NULL,
	PRIORITY        INT NOT NULL,
	PRICE           FLOAT NOT NULL,
	CURR		    VARCHAR(3)	NOT NULL,
	FOREIGN KEY (BRAND_ID) REFERENCES brands(ID)
);

CREATE INDEX IDX_PRICES_ID ON prices (ID);

